#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
簡單的 PDF 生成器
使用 reportlab 庫來生成 PDF 文件
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import cm


def create_simple_pdf(filename="output.pdf"):
    """
    建立一個簡單的 PDF 文件

    Args:
        filename: 輸出的 PDF 檔案名稱
    """
    # 建立 canvas 物件
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # 設定標題
    c.setFont("Helvetica-Bold", 24)
    c.drawString(2*cm, height - 3*cm, "TestyPDF - PDF Generator")

    # 設定副標題
    c.setFont("Helvetica", 16)
    c.drawString(2*cm, height - 5*cm, "This is a simple PDF generated by Python")

    # 繪製一些文字內容
    c.setFont("Helvetica", 12)
    y_position = height - 7*cm

    content = [
        "Features:",
        "- Generate PDF documents programmatically",
        "- Support for various fonts and styles",
        "- Easy to customize and extend",
        "",
        "Created with ReportLab library",
    ]

    for line in content:
        c.drawString(2*cm, y_position, line)
        y_position -= 0.7*cm

    # 繪製一個矩形
    c.setStrokeColorRGB(0.2, 0.5, 0.8)
    c.setFillColorRGB(0.8, 0.9, 1.0)
    c.rect(2*cm, y_position - 2*cm, 10*cm, 3*cm, fill=True, stroke=True)

    # 在矩形中加入文字
    c.setFillColorRGB(0, 0, 0)
    c.drawString(2.5*cm, y_position - 1*cm, "This is a colored box!")

    # 儲存 PDF
    c.save()
    print(f"PDF 文件已成功建立: {filename}")


if __name__ == "__main__":
    create_simple_pdf("output.pdf")
